services:
  - type: web
    name: hithisisme
    env: static
    staticPublishPath: ./public
    routes:
      - type: rewrite
        source: /things/*
        destination: /things/:splat
      - type: rewrite
        source: /*
        destination: /index.html
