services:
  - type: web
    name: hithisisme
    env: static
    staticPublishPath: ./public
    routes:
      - type: rewrite
        source: /things/*/*
        destination: /things/:category/:slug
      - type: rewrite
        source: /things/:category
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
